// ================================================================
// Generates, from the JSON source of truth in src/data/:
//   1. content/catalogue.md  — the offline master catalogue
//   2. supabase/seed.sql     — insert statements for the Supabase DB
// Run: npm run generate
// ================================================================
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dataDir = join(root, 'src', 'data')

const CATEGORIES = [
  { id: 'playful', name: 'Playful & Silly', emoji: '🎈', desc: 'Harmless teasing — safe for almost anyone' },
  { id: 'public', name: 'Safe in Public', emoji: '😌', desc: 'Mild enough for the office and grandma' },
  { id: 'banter', name: 'Best-Friend Banter', emoji: '🤝', desc: 'For people who will laugh, not sue' },
  { id: 'frustration', name: 'Everyday Frustration', emoji: '🤦', desc: 'Traffic, stubbed toes, Mondays' },
  { id: 'nuclear', name: 'Full Send', emoji: '💥', desc: 'Explicit. Know them — think twice before throwing them' }
]

const langs = readdirSync(dataDir)
  .filter((f) => f.endsWith('.json'))
  .map((f) => JSON.parse(readFileSync(join(dataDir, f), 'utf8')))
  .sort((a, b) => (a.status === b.status ? a.name.localeCompare(b.name) : a.status === 'full' ? -1 : 1))

// ---------- catalogue.md ----------
const sev = (s) => ['', '🟢 mild', '🟡 medium', '🔴 strong'][s]
let md = `# Insult Catalogue — Offline Master\n\n`
md += `> Source of truth is \`src/data/*.json\`. This file and \`supabase/seed.sql\` are generated from it — regenerate with \`npm run generate\` after editing.\n\n`
md += `**Total entries:** ${langs.reduce((n, l) => n + l.entries.length, 0)} across ${langs.length} languages.\n\n`
md += `## Content rules applied\n\n`
md += `All entries target universal, changeable traits or are general-purpose profanity. Terms that function as slurs against ethnicity, religion, gender, sexuality, disability, appearance, or any protected group were deliberately excluded — including several that are statistically "common" in their languages. Severity: 🟢 mild · 🟡 medium · 🔴 strong/explicit.\n\n`
md += `## Categories\n\n`
for (const c of CATEGORIES) md += `- ${c.emoji} **${c.name}** — ${c.desc}\n`
md += `\n---\n`

for (const lang of langs) {
  md += `\n## ${lang.flag} ${lang.name} (${lang.native}) — ${lang.entries.length} entries ${lang.status === 'starter' ? '· *starter pack*' : ''}\n\n`
  if (lang.note) md += `> ${lang.note}\n\n`
  if (lang.variants.length > 1) md += `Variants: ${lang.variants.map((v) => `${v.flag} ${v.name} (\`${v.code}\`)`).join(' · ')}\n\n`
  md += `| Original | Phonetic | Meaning | Literally | Category | Severity | Variants | Note |\n`
  md += `|---|---|---|---|---|---|---|---|\n`
  for (const e of lang.entries) {
    const cat = CATEGORIES.find((c) => c.id === e.category)
    const esc = (s) => String(s).replaceAll('|', '\\|')
    md += `| **${esc(e.original)}** | ${esc(e.phonetic)} | ${esc(e.translation)} | ${esc(e.literal)} | ${cat.emoji} ${cat.name} | ${sev(e.severity)} | ${e.variants ? e.variants.join(', ') : 'all'} | ${esc(e.note)} |\n`
  }
}
writeFileSync(join(root, 'content', 'catalogue.md'), md)

// ---------- seed.sql ----------
const q = (s) => (s === null || s === undefined) ? 'null' : `'${String(s).replaceAll("'", "''")}'`
let sql = `-- Generated by scripts/generate.mjs — do not edit by hand.\n`
sql += `-- Run schema.sql first.\n\n`
sql += `truncate entry_variants, entries, variants, categories, languages cascade;\n\n`

sql += CATEGORIES.map((c, i) =>
  `insert into categories (id, name, emoji, description, sort_order) values (${q(c.id)}, ${q(c.name)}, ${q(c.emoji)}, ${q(c.desc)}, ${i});`
).join('\n') + '\n\n'

for (const lang of langs) {
  sql += `insert into languages (code, name, native_name, flag, status, note) values (${q(lang.code)}, ${q(lang.name)}, ${q(lang.native)}, ${q(lang.flag)}, ${q(lang.status)}, ${q(lang.note ?? null)});\n`
  for (const v of lang.variants) {
    sql += `insert into variants (code, language_code, name, flag) values (${q(v.code)}, ${q(lang.code)}, ${q(v.name)}, ${q(v.flag)});\n`
  }
  for (const e of lang.entries) {
    sql += `insert into entries (id, language_code, original, phonetic, translation, literal, note, category_id, severity) values (${q(e.id)}, ${q(lang.code)}, ${q(e.original)}, ${q(e.phonetic)}, ${q(e.translation)}, ${q(e.literal)}, ${q(e.note)}, ${q(e.category)}, ${e.severity});\n`
    if (e.variants) {
      for (const vc of e.variants) {
        sql += `insert into entry_variants (entry_id, variant_code) values (${q(e.id)}, ${q(vc)});\n`
      }
    }
  }
  sql += '\n'
}
writeFileSync(join(root, 'supabase', 'seed.sql'), sql)

console.log(`Generated catalogue.md and seed.sql — ${langs.length} languages, ${langs.reduce((n, l) => n + l.entries.length, 0)} entries.`)
